### ISSUE TITLE
Subdominator snap version

### ISSUE THREAD

**Issue by drcoccodrillus** [Stratus-Security/Subdominator#3]
I have tried your tool and although it is still at an early stage of development, I find it very useful. I have made a snap out of it which could be very useful for Linux users. Here are the links to the project.
Snap store: https://snapcraft.io/subdominator
GitHub repository: https://github.com/drcoccodrillus/snap-subdominator

I am here for asking to partecipate in the project and help maintaining the Subdominator snap.

**Comment by coj337** [comment]
Thanks for creating the snap! You're welcome to maintain it for now, at some point it will be great to get this merged into the CD pipeline so it doesn't need to be manually created with updates.
