### ISSUE TITLE
Easyredir 

### ISSUE THREAD

**Issue by dshieble** [Stratus-Security/Subdominator#6]
Thanks for sharing this awesome tool. 

I believe that EasyRedir is no longer vulnerable for subdomain takeovers. They now require hostname verification on the source hostname. See https://help.easyredir.com/en/articles/6810071-what-is-hostname-verification. 

It is possible that I am misunderstanding something about the expected flow. Please let me know if this is the case. Thanks!

**Comment by coj337** [comment]
Thanks for letting me know, even if it took me a few months! I confirmed they patched it at some point in January so I have removed the fingerprint 😃
